{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "d08921f6_6dbceb03",
        "filename": "tools/testrunner/objects/testcase.py",
        "patchSetId": 5
      },
      "lineNbr": 200,
      "author": {
        "id": 1162439
      },
      "writtenOn": "2021-05-19T07:20:28Z",
      "side": 1,
      "message": "I noticed this is never printed anywhere and tests with incompatible flags are treated as \u0027passed\u0027 completely silently. The only way to find out that a test actually failed is to run it without the test runner locally. That feels a bit dangerous.. Should we perhaps treat it as \u0027skipped\u0027 instead?",
      "revId": "09fb6ddcbae1c10c4e34dff70463a9c4def9a203",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}