{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "6157017b_95431f52",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1132654
      },
      "writtenOn": "2021-04-09T15:47:24Z",
      "side": 1,
      "message": "Seems like we have to deal with https://crbug.com/1197508 as well",
      "revId": "a9755d4c2479dde742ade9737347a60aeba283b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "bee1c945_5bc9038c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1132654
      },
      "writtenOn": "2021-04-12T15:23:33Z",
      "side": 1,
      "message": "Hi Stephen, \n\nFrom clusterfuzz we got the following issue:\n\n  d8.promise.setHooks(\n    () \u003d\u003e {throw \"asdfasd\"},\n    () \u003d\u003e {throw \"asdfasd\"},\n    () \u003d\u003e {throw \"asdfasd\"},\n    () \u003d\u003e {throw \"asdfasd\"},\n    () \u003d\u003e {throw \"asdfasd\"}\n  );\n\n  Promise.reject().catch()\n\n\nEssentially we don\u0027t handle throwing promise hooks well in the runtime (contexts.cc).\nCould you take a look?\n",
      "revId": "a9755d4c2479dde742ade9737347a60aeba283b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}